name: Deploy to GitHub

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 자동 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v2

      # 2. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Python 3.11 사용

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # requirements.txt에 정의된 모든 패키지 설치

      # 4. (옵션) 추가적인 테스트나 배포 스크립트 실행 가능
      # 예: - name: Run tests
      #        run: python -m unittest discover
